@startuml UseCaseDétaile
left to right direction
actor "Capteurs IoT" as IoT
actor "Administrateur" as Admin
actor "Analyste de données" as Analyst

rectangle "Hadoop" {
    rectangle "NameNode (Maître)" as NameNode {
        usecase "Répartir les tâches" as DistributeTasks
        usecase "Gérer le stockage des fichiers" as ManageStorage
    }
    rectangle "DataNodes (Esclaves)" {
        usecase "Stocker les données" as StoreData
        usecase "Exécuter MapReduce" as ExecuteMapReduce
    }
}

usecase "Collecter des données" as CollectData
usecase "Exporter les résultats" as ExportResults

IoT --> CollectData
CollectData --> ManageStorage
Admin --> ManageStorage
Admin --> DistributeTasks
DistributeTasks --> StoreData
DistributeTasks --> ExecuteMapReduce
ExecuteMapReduce --> ExportResults
Analyst --> ExportResults
@enduml